name: "anti-plagiarism-app"

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  postgres:
    platform: linux/amd64
    image: postgres:16-alpine
    ports:
      - "5436:5436"
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=anti-plagiarism
      - POSTGRES_SCHEMA=public
      - PGPORT=5436
  flyway:
    image: flyway/flyway:10.12.0-alpine
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=12345678
      - FLYWAY_URL=jdbc:postgresql://postgres:5436/anti-plagiarism
      - FLYWAY_SCHEMAS=public
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - $PWD/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
  backend:
    build: ./mono
    command: 

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - flyway
      - postgres
  frontend:
    build: ./anti-plagiarism-project
    volumes:
      - ./frontend/:/app/
    ports:
      - 3000:3000
  # engine-switcher:
  #   build: ./engine-switcher
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./compose/nginx/Dockerfile
  #   depends_on:
  #     - django
  #     - node
  #   volumes:
  #     - ./staticfiles/:/app/staticfiles
  #     - ./uploads/:/app/uploads
  #     - ./compose/nginx/certs:/certs
  #   ports:
  #     - "9001:443"