version: "1"
name: "anti-plagiarism-app"

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  postgres:
    platform: linux/amd64
    image: postgres:16-alpine
    ports:
      - 5436:5436
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=anti-plagiarism
      - POSTGRES_SCHEMA=public
      - PGPORT=5436
  flyway:
    image: flyway/flyway:10.12.0-alpine
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=12345678
      - FLYWAY_URL=jdbc:postgresql://postgres:5436/anti-plagiarism
      - FLYWAY_SCHEMAS=public
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - $PWD/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
  backend:
    build:
      context: .
      dockerfile: ./mono/Dockerfile
    depends_on:
      - flyaway
      - postgres
    ports:
    # TBD
  client:
    build:
      context: .
      dockerfile: ./anti-plagiarism-project/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./client/:/app/
    env_file:
    ports:
      - "9090:8080" # npm run serve port
      - "3000:3000" # ui port
    command: /start.sh
  engine-switcher:
    build:
      context: .
      dockerfile: ./engine-switcher/Dockerfile
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./compose/nginx/Dockerfile
  #   depends_on:
  #     - django
  #     - node
  #   volumes:
  #     - ./staticfiles/:/app/staticfiles
  #     - ./uploads/:/app/uploads
  #     - ./compose/nginx/certs:/certs
  #   ports:
  #     - "9001:443"